# .github/workflows/update_students.yml
name: Update Student Repositories

on:
  push:
    branches:
      - main

jobs:
  update-students:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        gh auth status

    - name: Get List of Student Repositories
      id: get_repos
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        echo "Fetching student repositories..."
        gh api orgs/cmse822/repos --paginate --jq '.[] | select(.name | startswith("cmse822-ss25-")) | .name' > student_repos.txt
        echo "Student repositories found:"
        cat student_repos.txt

    - name: Create Pull Requests in Student Repositories
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        TEMPLATE_REPO="cmse822/cmse822-codex-ss25"
        TEMPLATE_BRANCH="main"

        while read repo; do
          echo "Processing repository: $repo"

          # Attempt to create a PR directly from template/main → student/main
          gh pr create --repo cmse822/$repo \
            --head $TEMPLATE_REPO:$TEMPLATE_BRANCH \
            --base main \
            --title "Update from Template Repository" \
            --body "This pull request includes updates from the template repository's main branch. Please review and merge to incorporate the latest changes." || {
              echo "Error: Failed to create PR in $repo"
              continue
            }

          echo "Pull request created for repository: $repo"
          sleep 2  # Prevent rate-limiting issues

        done < student_repos.txt
