# .github/workflows/update_students.yml
name: Update Student Repositories

on:
  push:
    branches:
      - main

jobs:
  update-students:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Template Repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        gh auth status

    - name: Get List of Student Repositories
      id: get_repos
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        echo "Fetching student repositories..."
        gh api orgs/cmse822/repos --paginate --jq '.[] | select(.name | startswith("cmse822-ss25-")) | .name' > student_repos.txt
        echo "Student repositories found:"
        cat student_repos.txt

    - name: Create Pull Requests in Student Repositories
      env:
        GITHUB_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        TEMPLATE_REPO="cmse822/cmse822-codex-ss25"
        TEMPLATE_BRANCH="main"

        while read repo; do
          echo "Processing repository: $repo"

          # Get the SHA of the student's `main` branch (not the template repo's SHA)
          STUDENT_MAIN_SHA=$(gh api repos/cmse822/$repo/git/refs/heads/main --jq .object.sha 2>/dev/null || echo "")

          if [[ -z "$STUDENT_MAIN_SHA" ]]; then
            echo "Error: Could not retrieve SHA for main branch in $repo. Skipping..."
            continue
          fi

          # Define a unique branch name for the PR
          NEW_BRANCH="update-from-template-$(date +%s)"
          TARGET_BRANCH="main"

          echo "Creating new branch $NEW_BRANCH in $repo from student repo's main branch ($STUDENT_MAIN_SHA)"

          # Create a new branch in the student repo from its own main branch
          gh api repos/cmse822/$repo/git/refs -X POST -f ref="refs/heads/$NEW_BRANCH" -f sha="$STUDENT_MAIN_SHA" || {
            echo "Error: Failed to create branch in $repo"
            continue
          }

          # Pull changes from the template repo
          echo "Merging changes from template into $NEW_BRANCH..."
          gh api repos/cmse822/$repo/merges -X POST -f base=$NEW_BRANCH -f head=$TEMPLATE_REPO:$TEMPLATE_BRANCH || {
            echo "Error: Merge failed for $repo"
            continue
          }

          # Create a pull request
          echo "Creating pull request in $repo"
          gh pr create --repo cmse822/$repo --head $NEW_BRANCH --base $TARGET_BRANCH --title "Update from Template Repository" --body "This PR merges updates from the template repository. Please review and merge." || {
            echo "Error: Failed to create PR in $repo"
            continue
          }

          echo "Pull request created for repository: $repo"
          sleep 2  # Prevent rate-limiting issues

        done < student_repos.txt
